# your domain
domain: proxypoolss.herokuapp.com
#domain: 127.0.0.1:8080

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - ./config/source.yaml
  # use web file
#  - https://proxypoolss.herokuapp.com/config/source.yaml
